### PR TITLE
feat(widget): expose pulse to the widget (to get volume and mute status)

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by mokasin** [comment]
Why do you want to let the widget expose pulse? Can you explain your use case? Seems to me, that would be only needed to move logic into your configuration file, which I personally would discourage.

Thx for your contribution.

**Comment by actionless** [comment]
no, as i stated in the commit message, i just need to know mute and volume frmo the outside of the widget

**Comment by mokasin** [comment]
So basically *pulseaudio.lua* should be a separate module apart from the widget itself, in order to do this cleanly. But I guess, since the change is really marginal, it wouldn't really hurt.

**Comment by actionless** [comment]
thanks!

**Pull request merged**
